### ISSUE TITLE
Normal issue

### ISSUE THREAD

**Issue by eansell3** [OxfordTechnicalSolutions/test_repo#4] opened 2021-09-23 16:14 UTC
I'm an OxTS member and I have a problem.

**Comment by eansell** [comment] 2021-09-23 16:14
comment

**Comment by eansell3** [comment] 2021-09-23 16:15
another comment

**Comment by eansell3** [comment] 2021-09-23 16:15
@eansell direct mention

**Comment by eansell3** [comment] 2021-09-23 16:15
> 
> 
> comment

quotoe

**Comment by eansell4** [comment] 2021-09-23 16:25
I shouldn't have permission to close this.
The [docs say I can't close this](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization) with Read acess and the [access list from the owner's account](https://github.com/orgs/OxfordTechnicalSolutions/people/eansell4) says I only have Read access to this repository yet here I am closing it anyway.

**Comment by eansell4** [comment] 2021-09-23 16:26
Hang on, it's still open! There was a "close with comment" button but it's still open!!! The button is gone, as it should be!!! No idea what happened but there is a God!!!!

Absolutely elated. Overwhelmed with relief

**Comment by eansell4** [comment] 2021-09-23 16:28
Now I'm part of the support team, I can close it. Thank goodness it's working as intended

**Closed by eansell4** 2021-09-23 16:28 UTC
